name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install main dependencies
      run: npm ci

    - name: Build jslog
      run: npm run build

    - name: Install benchmark dependencies
      working-directory: ./benchmarks
      run: npm ci

    - name: Run benchmarks
      working-directory: ./benchmarks
      run: |
        echo "Running benchmarks..."
        npm run bench
        npm run bench:report

    - name: Display benchmark results
      if: always()
      run: |
        echo "# Benchmark Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -f benchmarks/BENCH.md ]; then
          cat benchmarks/BENCH.md >> $GITHUB_STEP_SUMMARY
        else
          echo "Benchmark results file not found" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload benchmark results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmarks/BENCH.md
        retention-days: 30
