name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npm run typecheck

    - name: Build
      run: npm run build

    - name: Run tests with assertions
      id: tests
      run: npm test
      continue-on-error: true

    - name: Test results summary
      if: always()
      run: |
        echo "# Test Results - Node.js ${{ matrix.node-version }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.tests.outcome }}" == "success" ]; then
          echo "**Status:** PASSED" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All example tests passed validation" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tests validated:**" >> $GITHUB_STEP_SUMMARY
          echo "- Basic logging features" >> $GITHUB_STEP_SUMMARY
          echo "- Advanced features (LevelVar, all attribute types, groups, etc)" >> $GITHUB_STEP_SUMMARY
          echo "- Beast mode features (20+ advanced features)" >> $GITHUB_STEP_SUMMARY
        else
          echo "**Status:** FAILED" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Test validation failed" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Fail job if tests failed
      if: steps.tests.outcome != 'success'
      run: exit 1
